config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'admin/products#index'

  scope  :module => "admin", :as => 'admin', :path => 'fiddle' do
    resources :catalog, only: [:new, :create]
    resources :products, only: :index
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
require 'csv'

class Product < ApplicationRecord
  VISIBLE_FIELDS = [
    :product_category, :value, :product_name, :vendor,
    :phone, :customer_name, :zip_code, :city, :street 
  ]

  scope :periphery, -> { where.not(city: ['Москва', 'Санкт-Петербург']) }
  
  def self.load(file)
    return unless file.respond_to? :tempfile
    
    destroy_all

    CSV.foreach(file.tempfile, :headers => true, :col_sep => ';') do |unstripped|
      row = {}
      unstripped.each { |k, v| row[k.strip] = v.strip }
      create(row.to_hash)
    end

    true
  rescue
    false
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable

end

app/controllers/admin/catalog_controller.rb
class Admin::CatalogController < AdminController
  rescue_from ActionController::ParameterMissing do  
    flash[:notice] = t '.file_missing'
    redirect_back(fallback_location: root_path)
  end

  def new
  end

  def create
    if Product.load catalog_params[:file]
      redirect_to root_path
    else
      flash[:error] = t '.load_error'
      redirect_back(fallback_location: root_path)
    end
  end

  private

  def catalog_params
    params.require(:catalog).permit(:file)
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < AdminController
  def index
    @fields = Product::VISIBLE_FIELDS
    @products = Product.periphery.order(value: :desc).limit(10)
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_user!, :provide_user
  rescue_from CanCan::AccessDenied do
    head :forbidden
  end

  private

  def provide_user
    @user = current_user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/admin/catalog_helper.rb
module Admin::CatalogHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/catalog/new.html.haml
%h1 Загрузка каталога в формате *.csv

.container__catalog
  - flash.each do |k, msg|
    %p.flash{ class: "flash__#{k}" }= msg
  
  = form_tag(admin_catalog_index_path, multipart: true) do |f|
    = file_field :catalog, :file, accept: ".csv"
    %br


    = submit_tag '', class: 'hidden'
    .btn.btn-default.btn_upload.icon-upload-cloud Загрузить данные из файла в хранилище

= content_for :head do
  = tag(:meta, name: 'turbolinks-cache-control', content: 'no-cache')

app/views/admin/layouts/_header.html.haml
%header.header
  .header__inner.admin
    
    %h1.header__logo= link_to 'Logo picture', root_path, class: 'logo-picture'
    
    %ul.header-user-profile
      %li.avatar= link_to '', 'https://github.com/gafrom', title: "Профиль", class: "avatar-female"
      %li.profile
        %p Всемогущий
        %p.dim Загружальщик
    
    .header_menu_block  
      %ul.social-icons.social-icons_header
        %li= link_to '', 'https://github.com/gafrom/fiddle', class: 'icon-github-circled', title: "Source code"

      %ul.header__menu
        %li= link_to 'Загрузить CSV', new_admin_catalog_path, title: "Загрузить CSV"
        %li= link_to 'Показать 10 топ', root_path, title: "Показать 10 топ"
        %li= link_to 'Выйти', destroy_user_session_path, method: :delete, title: "Выйти" 


    %button.header__hamburger
      %span

app/views/admin/products/_product.html.haml
%tr.fallable
  - @fields.each do |field|
    %td= product[field]

app/views/admin/products/index.html.haml
%h1 Данные из хранилища
%h5
  %i Топ 10 товаров, купленных жителями не из Москвы и Питера

- if @products.empty?
  %p= link_to t('.upload_file'), new_admin_catalog_path

- else
  %table
    %thead
      %tr
        - @fields.each do |field|
          %th= t ".#{field}"

    %tbody.fallable-list
      =render @products

app/views/layouts/_footer.html.haml
%footer.footer{id: 'footer', data: { "turbolinks-permanent": true } }
  .footer__inner
    %ul.footer__col.footer__col_first
      %li= link_to 'Загрузить CSV', new_admin_catalog_path
      %li= link_to 'Показать 10 топ', root_path
      %li.mobile-only= link_to 'Контакты', '#'

    .footer__col.footer__col_second
      %h5.footer-col__title Магия ответов
      %a.footer-col__magic.icon-flag-checkered{ href: "mailto:gafrom@gmail.com?SUBJECT=#{URI.escape(t 'mail.subject')}&BODY=#{URI.escape(t 'mail.body')}" }
        %span.address__text
          %span.address__city Отправить Job offer
          %span.address__street Из любимого почтового клиента
      %a.footer-col__magic.icon-award{:href => "tel:+79237405786"}
        %span.address__text
          %span.address__city Позвонить
          %span.address__street Обсудить условия предложения

    .footer__col.footer__col_third
      %h5.footer-col__title Мои контакты
      %p.footer-col__p
        %span= link_to 'gafrom@gmail.com', 'mailto:gafrom@gmail.com'
        %span
          Тел.:
          %a.footer__tel-link{:href => "tel:+79237405786"} +7 (923) 740 57 86

  %ul.social-icons.social-icons_footer
    %li= link_to '', 'https://github.com/gafrom/fiddle', class: 'icon-github-circled'

  %p.footer__copyrights © 2016 Тестовое задание

app/views/layouts/_header.html.haml
%body
  %header.header
    .header__inner
      %h1.header__logo= link_to 'Fiddle test app', root_path, class: 'logo-picture'
      %ul.social-icons.social-icons_header
        %li= link_to '', 'https://github.com/gafrom/fiddle', class: 'icon-github-circled', title: "Source code"

      %ul.header__menu
        %li= link_to 'Загрузить CSV', new_admin_catalog_path, title: "Загрузить CSV"
        %li= link_to 'Показать 10 топ', root_path, title: "Показать 10 топ"

      %button.header__hamburger
        %span

app/views/layouts/_meta_tags.html.haml
%meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
%meta{:charset => "utf-8"}/
%meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}/
%meta{:content => "width=device-width, initial-scale=1.0, user-scalable=no", :name => "viewport"}/

%link{:href => "https://fonts.googleapis.com/css?family=Arimo:400,400italic,700,700italic&subset=latin,cyrillic", :rel => "stylesheet", :type => "text/css"}/
%link{:href => "https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800,400italic&subset=latin,cyrillic", :rel => "stylesheet", :type => "text/css"}/

app/views/layouts/application.html.haml
!!! html

%html{:lang => "ru"}
  %head
    %title= @title || "Каталог"

    = yield(:head) if content_for?(:head)
    = csrf_meta_tags
    = render 'layouts/meta_tags'

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    - if controller.kind_of? AdminController
      = render 'admin/layouts/header'
    - else
      = render 'layouts/header'

    .container= yield
    
    = render 'layouts/footer'